languages = ["css", "html", "php", "cpp", "js"]

[editor]
name = "name"
config_path = "config"
binary_path = "Option"
files_path = "Option"

[package.node]
name = "node"

[package.npm]
name = "npm"

[package.css]
name = "css"
path = "coucou"
require = ["npm", "node"]

[package.php]
name = "css"
path = "coucou"
