languages = ["css", "html", "php", "cpp", "js"]

[editor]
name = "name"
config_path = "config"
binary_path = "Option"
files_path = "Option"

# [language_config]
[language_config.css]
name = "css"
path = "coucou"
require = ["php", "css"]

[language_config.php]
name = "css"
path = "coucou"
